### ISSUE TITLE
Build broken?

### ISSUE THREAD

**Issue by pikeas** [just-containers/skaware#10]
```
./tools/install.sh -D tools/musl-gcc /skarnet-builder/pkg/musl/bin/musl-gcc
+ cd /skarnet-builder/build
+ curl -R -L -O -C - http://www.kernel.org/pub/linux/kernel/v3.x/linux-3.18.5.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                             Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0   1750      0 --:--:-- --:--:-- --:--:--  1762
100 77.2M  100 77.2M    0     0  1495k      0  0:00:52  0:00:52 --:--:-- 1660k
+ tar xf linux-3.18.5.tar.xz
tar: linux-3.18.5/arch/arm/boot/dts/include: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
```

**Comment by glerchundi** [comment]
Hi @pikeas,

Build is working in [travis](https://travis-ci.org/just-containers/skaware-builder) so it must be something related to your environment, how are you building it? using docker or manually? If you were using docker, make sure your dist folder has correct perms for nobody.

And if you just wanted to have releases, latest are published in our github releases.

**Comment by glerchundi** [comment]
no news good news :-), closing this issue.

**Comment by pikeas** [comment]
Yep, sorry for not following up - bad permissions on the folder I was mounting in.
