### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by glerchundi** [just-containers/skaware#13]
We need to decide how to version our releases:
`<major>.<minor>.<version>`:
- `<major>`: big/breaking changes in skaware.
- `<minor>`: backward compatible changes in skaware due to new functions/utilities or bug fixes.
- `<version>`: changes in packaging/builds/etc, or bug fixes dependant packages, like musl.

So the latest version should have been tagged as 1.9.1 and not as 1.10.0, but @jprjr what do you think?

**Comment by jprjr** [comment]
Sounds good to me!

I got thrown off by this in the overlay builder: https://github.com/just-containers/s6-overlay-builder/blob/master/builder/build-latest#L9-L10

```
RELEASE_VERSION=${RELEASE_VERSION:-1.10.0}
SKAWARE_VERSION=${RELEASE_VERSION%.*}.0
```

That looks like it'll always pull the .0 release from skaware builder, I think? So if I made that last version 1.9.1, the overlay builder would still pull 1.9.0? I'm not sure though.

**Comment by glerchundi** [comment]
Ha! I didn't realized of that. What we can do is use 4 digits for s6-overlay versioning. So that we can do something like this:

```
RELEASE_VERSION=${RELEASE_VERSION:-1.9.1.0}
SKAWARE_VERSION=${RELEASE_VERSION%.*}
```

Last digit will refer to the revision of s6-overlay itself.

I'm going to do it as an example, ok? :-)

**Comment by jprjr** [comment]
Sounds awesome!

**Comment by glerchundi** [comment]
done! just-containers/s6-overlay-builder#31.
