### ISSUE TITLE
armv7l

### ISSUE THREAD

**Issue by hurricanehrndz** [just-containers/skaware#32]
Any chances we can get an arm build?

**Comment by glerchundi** [comment]
First musl should be compiled for arm too, http://wiki.musl-libc.org/wiki/Getting_started#Building_a_cross_compiler_targeting_musl_libc. And then build skarnet software in it which I don't know if it's possible or not. Although, the best place to ask these questions is the supervision list.

Do you have something concrete in mind? Maybe for buildroot or something like that?

**Comment by hurricanehrndz** [comment]
Well, I will give it a shot and report back. I am using qemu with linaro vexpress images as my build environment, running Ubuntu of course, no cross compiling.  

The results will be used for docker images being deployed to arm devices.

**Comment by hurricanehrndz** [comment]
If I'm using this for docker only, I only need the portable packages, right?

**Comment by glerchundi** [comment]
If you're using `s6-overlay`, [`yes`](https://github.com/just-containers/s6-overlay/blob/master/builder/build-latest#L17), u just need the [`portable items`](https://github.com/just-containers/skaware/releases/download/v1.17.0/manifest-portable.txt).

**Comment by hurricanehrndz** [comment]
Awesome, I got it compiled with minimal effort.  Thanks so much. If you like I can document the process.

**Comment by hurricanehrndz** [comment]
All the packages say amd64, but that's because that's how it was hard coded. Kind of funny.

**Comment by glerchundi** [comment]
> Awesome, I got it compiled with minimal effort. Thanks so much. If you like I can document the process.

I will really appreciate it! Having a arm-compatible version would be an interesting move toward container-capable embedded systems!

**Comment by hurricanehrndz** [comment]
Okay,

I have upload my results and builder to my fork of this [project](https://github.com/hurricanehrndz/skaware/tree/armv7l)

You might want to take a look at [this](https://github.com/hurricanehrndz/skaware/tree/armv7l) if your are using travis.

**Comment by glerchundi** [comment]
Thanks! :+1:
